version: "3"

services:
  db:
    image: mysql
    restart: on-failure
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE='pronuance'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='root'
      - MYSQL_ROOT_PASSWORD='root'
    ports:
      - "8001:3306"
    container_name: pronuance_db

  web:
    build: .
    env_file: .env
    restart: on-failure
    volumes:
      - .:/django
    working_dir: "/django"
    ports:
      - "8000:8000"
    image: pronuance_django
    container_name: pronuance_web
    depends_on:
      - db
    links:
      - "db"
