# Generated by Django 4.0.3 on 2022-04-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
